var annotated_dup =
[
    [ "rtt", "namespacertt.html", [
      [ "ai", "namespacertt_1_1ai.html", [
        [ "control", "namespacertt_1_1ai_1_1control.html", [
          [ "ControlModule", "classrtt_1_1ai_1_1control_1_1ControlModule.html", "classrtt_1_1ai_1_1control_1_1ControlModule" ],
          [ "ControlUtils", "classrtt_1_1ai_1_1control_1_1ControlUtils.html", "classrtt_1_1ai_1_1control_1_1ControlUtils" ],
          [ "CollisionDetector", "classrtt_1_1ai_1_1control_1_1CollisionDetector.html", "classrtt_1_1ai_1_1control_1_1CollisionDetector" ],
          [ "NumTreesPlanning", "classrtt_1_1ai_1_1control_1_1NumTreesPlanning.html", "classrtt_1_1ai_1_1control_1_1NumTreesPlanning" ],
          [ "PathPlanningAlgorithm", "classrtt_1_1ai_1_1control_1_1PathPlanningAlgorithm.html", "classrtt_1_1ai_1_1control_1_1PathPlanningAlgorithm" ],
          [ "GraphNode", "namespacertt_1_1ai_1_1control.html#structrtt_1_1ai_1_1control_1_1GraphNode", "namespacertt_1_1ai_1_1control_structrtt_1_1ai_1_1control_1_1GraphNode_dup" ],
          [ "VoronoiPathPlanning", "classrtt_1_1ai_1_1control_1_1VoronoiPathPlanning.html", "classrtt_1_1ai_1_1control_1_1VoronoiPathPlanning" ],
          [ "PathPointNode", "classrtt_1_1ai_1_1control_1_1PathPointNode.html", "classrtt_1_1ai_1_1control_1_1PathPointNode" ],
          [ "BBTPathTracking", "classrtt_1_1ai_1_1control_1_1BBTPathTracking.html", "classrtt_1_1ai_1_1control_1_1BBTPathTracking" ],
          [ "DensePathTracking", "classrtt_1_1ai_1_1control_1_1DensePathTracking.html", "classrtt_1_1ai_1_1control_1_1DensePathTracking" ],
          [ "PathTrackingAlgorithm", "classrtt_1_1ai_1_1control_1_1PathTrackingAlgorithm.html", "classrtt_1_1ai_1_1control_1_1PathTrackingAlgorithm" ],
          [ "PidTracking", "classrtt_1_1ai_1_1control_1_1PidTracking.html", "classrtt_1_1ai_1_1control_1_1PidTracking" ],
          [ "PositionControl", "classrtt_1_1ai_1_1control_1_1PositionControl.html", "classrtt_1_1ai_1_1control_1_1PositionControl" ],
          [ "PositionControlUtils", "classrtt_1_1ai_1_1control_1_1PositionControlUtils.html", "classrtt_1_1ai_1_1control_1_1PositionControlUtils" ]
        ] ],
        [ "interface", "namespacertt_1_1ai_1_1interface.html", [
          [ "Drawing", "structrtt_1_1ai_1_1interface_1_1Drawing.html", "structrtt_1_1ai_1_1interface_1_1Drawing" ],
          [ "Input", "classrtt_1_1ai_1_1interface_1_1Input.html", "classrtt_1_1ai_1_1interface_1_1Input" ],
          [ "Output", "classrtt_1_1ai_1_1interface_1_1Output.html", "classrtt_1_1ai_1_1interface_1_1Output" ],
          [ "Toggle", "classrtt_1_1ai_1_1interface_1_1Toggle.html", "classrtt_1_1ai_1_1interface_1_1Toggle" ],
          [ "Toggles", "classrtt_1_1ai_1_1interface_1_1Toggles.html", "classrtt_1_1ai_1_1interface_1_1Toggles" ],
          [ "GraphWidget", "classrtt_1_1ai_1_1interface_1_1GraphWidget.html", "classrtt_1_1ai_1_1interface_1_1GraphWidget" ],
          [ "MainControlsWidget", "classrtt_1_1ai_1_1interface_1_1MainControlsWidget.html", "classrtt_1_1ai_1_1interface_1_1MainControlsWidget" ],
          [ "MainWindow", "classrtt_1_1ai_1_1interface_1_1MainWindow.html", "classrtt_1_1ai_1_1interface_1_1MainWindow" ],
          [ "ManualControlWidget", "classrtt_1_1ai_1_1interface_1_1ManualControlWidget.html", "classrtt_1_1ai_1_1interface_1_1ManualControlWidget" ],
          [ "PidBox", "classrtt_1_1ai_1_1interface_1_1PidBox.html", "classrtt_1_1ai_1_1interface_1_1PidBox" ],
          [ "PidsWidget", "classrtt_1_1ai_1_1interface_1_1PidsWidget.html", "classrtt_1_1ai_1_1interface_1_1PidsWidget" ],
          [ "PlaysWidget", "classrtt_1_1ai_1_1interface_1_1PlaysWidget.html", "classrtt_1_1ai_1_1interface_1_1PlaysWidget" ],
          [ "RobotsWidget", "classrtt_1_1ai_1_1interface_1_1RobotsWidget.html", "classrtt_1_1ai_1_1interface_1_1RobotsWidget" ],
          [ "RuleSetWidget", "classrtt_1_1ai_1_1interface_1_1RuleSetWidget.html", "classrtt_1_1ai_1_1interface_1_1RuleSetWidget" ],
          [ "SettingsWidget", "classrtt_1_1ai_1_1interface_1_1SettingsWidget.html", "classrtt_1_1ai_1_1interface_1_1SettingsWidget" ],
          [ "STPVisualizerWidget", "classrtt_1_1ai_1_1interface_1_1STPVisualizerWidget.html", "classrtt_1_1ai_1_1interface_1_1STPVisualizerWidget" ],
          [ "VisualizationSettingsWidget", "classrtt_1_1ai_1_1interface_1_1VisualizationSettingsWidget.html", "classrtt_1_1ai_1_1interface_1_1VisualizationSettingsWidget" ],
          [ "Visualizer", "classrtt_1_1ai_1_1interface_1_1Visualizer.html", "classrtt_1_1ai_1_1interface_1_1Visualizer" ]
        ] ],
        [ "io", "namespacertt_1_1ai_1_1io.html", [
          [ "IOManager", "classrtt_1_1ai_1_1io_1_1IOManager.html", "classrtt_1_1ai_1_1io_1_1IOManager" ]
        ] ],
        [ "stp", "namespacertt_1_1ai_1_1stp.html", [
          [ "computations", "namespacertt_1_1ai_1_1stp_1_1computations.html", [
            [ "GoalComputations", "classrtt_1_1ai_1_1stp_1_1computations_1_1GoalComputations.html", "classrtt_1_1ai_1_1stp_1_1computations_1_1GoalComputations" ],
            [ "PassComputations", "classrtt_1_1ai_1_1stp_1_1computations_1_1PassComputations.html", "classrtt_1_1ai_1_1stp_1_1computations_1_1PassComputations" ]
          ] ],
          [ "evaluation", "namespacertt_1_1ai_1_1stp_1_1evaluation.html", [
            [ "BaseEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BaseEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BaseEvaluation" ],
            [ "BallPlacementThemGameStateEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallPlacementThemGameStateEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallPlacementThemGameStateEvaluation" ],
            [ "BallPlacementUsGameStateEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallPlacementUsGameStateEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallPlacementUsGameStateEvaluation" ],
            [ "FreeKickThemGameStateEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1FreeKickThemGameStateEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1FreeKickThemGameStateEvaluation" ],
            [ "FreeKickUsGameStateEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1FreeKickUsGameStateEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1FreeKickUsGameStateEvaluation" ],
            [ "HaltGameStateEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1HaltGameStateEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1HaltGameStateEvaluation" ],
            [ "KickOffThemGameStateEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1KickOffThemGameStateEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1KickOffThemGameStateEvaluation" ],
            [ "KickOffThemPrepareGameStateEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1KickOffThemPrepareGameStateEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1KickOffThemPrepareGameStateEvaluation" ],
            [ "KickOffUsGameStateEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1KickOffUsGameStateEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1KickOffUsGameStateEvaluation" ],
            [ "KickOffUsOrNormalGameStateEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1KickOffUsOrNormalGameStateEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1KickOffUsOrNormalGameStateEvaluation" ],
            [ "KickOffUsPrepareGameStateEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1KickOffUsPrepareGameStateEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1KickOffUsPrepareGameStateEvaluation" ],
            [ "NormalOrFreeKickUsGameStateEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1NormalOrFreeKickUsGameStateEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1NormalOrFreeKickUsGameStateEvaluation" ],
            [ "NormalPlayGameStateEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1NormalPlayGameStateEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1NormalPlayGameStateEvaluation" ],
            [ "PenaltyThemGameStateEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1PenaltyThemGameStateEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1PenaltyThemGameStateEvaluation" ],
            [ "PenaltyThemPrepareGameStateEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1PenaltyThemPrepareGameStateEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1PenaltyThemPrepareGameStateEvaluation" ],
            [ "PenaltyUsGameStateEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1PenaltyUsGameStateEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1PenaltyUsGameStateEvaluation" ],
            [ "PenaltyUsPrepareGameStateEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1PenaltyUsPrepareGameStateEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1PenaltyUsPrepareGameStateEvaluation" ],
            [ "PreHalfGameStateEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1PreHalfGameStateEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1PreHalfGameStateEvaluation" ],
            [ "StopGameStateEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1StopGameStateEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1StopGameStateEvaluation" ],
            [ "TimeOutGameStateEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1TimeOutGameStateEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1TimeOutGameStateEvaluation" ],
            [ "BallClosestToUsGlobalEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallClosestToUsGlobalEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallClosestToUsGlobalEvaluation" ],
            [ "BallCloseToThemGlobalEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallCloseToThemGlobalEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallCloseToThemGlobalEvaluation" ],
            [ "BallCloseToUsGlobalEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallCloseToUsGlobalEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallCloseToUsGlobalEvaluation" ],
            [ "BallGotShotGlobalEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallGotShotGlobalEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallGotShotGlobalEvaluation" ],
            [ "BallInOurDefenseAreaAndStillGlobalEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallInOurDefenseAreaAndStillGlobalEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallInOurDefenseAreaAndStillGlobalEvaluation" ],
            [ "BallIsFreeGlobalEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallIsFreeGlobalEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallIsFreeGlobalEvaluation" ],
            [ "BallMovesSlowGlobalEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallMovesSlowGlobalEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallMovesSlowGlobalEvaluation" ],
            [ "BallNotInOurDefenseAreaAndStillGlobalEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallNotInOurDefenseAreaAndStillGlobalEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallNotInOurDefenseAreaAndStillGlobalEvaluation" ],
            [ "BallOnOurSideGlobalEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallOnOurSideGlobalEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallOnOurSideGlobalEvaluation" ],
            [ "BallOnTheirSideGlobalEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallOnTheirSideGlobalEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallOnTheirSideGlobalEvaluation" ],
            [ "DistanceFromBallGlobalEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1DistanceFromBallGlobalEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1DistanceFromBallGlobalEvaluation" ],
            [ "FreedomOfRobotsGlobalEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1FreedomOfRobotsGlobalEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1FreedomOfRobotsGlobalEvaluation" ],
            [ "GoalVisionFromBallGlobalEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1GoalVisionFromBallGlobalEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1GoalVisionFromBallGlobalEvaluation" ],
            [ "GoalVisionGlobalEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1GoalVisionGlobalEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1GoalVisionGlobalEvaluation" ],
            [ "NoGoalVisionFromBallGlobalEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1NoGoalVisionFromBallGlobalEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1NoGoalVisionFromBallGlobalEvaluation" ],
            [ "TheyDoNotHaveBallGlobalEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1TheyDoNotHaveBallGlobalEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1TheyDoNotHaveBallGlobalEvaluation" ],
            [ "TheyHaveBallGlobalEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1TheyHaveBallGlobalEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1TheyHaveBallGlobalEvaluation" ],
            [ "WeHaveBallGlobalEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1WeHaveBallGlobalEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1WeHaveBallGlobalEvaluation" ],
            [ "WeHaveMajorityGlobalEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1WeHaveMajorityGlobalEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1WeHaveMajorityGlobalEvaluation" ],
            [ "BlockingEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BlockingEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BlockingEvaluation" ],
            [ "GoalShotEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1GoalShotEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1GoalShotEvaluation" ],
            [ "LineOfSightEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1LineOfSightEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1LineOfSightEvaluation" ],
            [ "OpennessEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1OpennessEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1OpennessEvaluation" ],
            [ "TimeToPositionEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1TimeToPositionEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1TimeToPositionEvaluation" ]
          ] ],
          [ "gen", "namespacertt_1_1ai_1_1stp_1_1gen.html", [
            [ "PositionScores", "namespacertt_1_1ai_1_1stp_1_1gen.html#structrtt_1_1ai_1_1stp_1_1gen_1_1PositionScores", "namespacertt_1_1ai_1_1stp_1_1gen_structrtt_1_1ai_1_1stp_1_1gen_1_1PositionScores_dup" ],
            [ "ScoreProfile", "namespacertt_1_1ai_1_1stp_1_1gen.html#structrtt_1_1ai_1_1stp_1_1gen_1_1ScoreProfile", "namespacertt_1_1ai_1_1stp_1_1gen_structrtt_1_1ai_1_1stp_1_1gen_1_1ScoreProfile_dup" ],
            [ "ScoredPosition", "namespacertt_1_1ai_1_1stp_1_1gen.html#structrtt_1_1ai_1_1stp_1_1gen_1_1ScoredPosition", "namespacertt_1_1ai_1_1stp_1_1gen_structrtt_1_1ai_1_1stp_1_1gen_1_1ScoredPosition_dup" ],
            [ "StoreInfo", "namespacertt_1_1ai_1_1stp_1_1gen.html#structrtt_1_1ai_1_1stp_1_1gen_1_1StoreInfo", "namespacertt_1_1ai_1_1stp_1_1gen_structrtt_1_1ai_1_1stp_1_1gen_1_1StoreInfo_dup" ]
          ] ],
          [ "play", "namespacertt_1_1ai_1_1stp_1_1play.html", [
            [ "GetBallPossession", "classrtt_1_1ai_1_1stp_1_1play_1_1GetBallPossession.html", "classrtt_1_1ai_1_1stp_1_1play_1_1GetBallPossession" ],
            [ "GetBallRisky", "classrtt_1_1ai_1_1stp_1_1play_1_1GetBallRisky.html", "classrtt_1_1ai_1_1stp_1_1play_1_1GetBallRisky" ],
            [ "DefendPass", "classrtt_1_1ai_1_1stp_1_1play_1_1DefendPass.html", "classrtt_1_1ai_1_1stp_1_1play_1_1DefendPass" ],
            [ "DefendShot", "classrtt_1_1ai_1_1stp_1_1play_1_1DefendShot.html", "classrtt_1_1ai_1_1stp_1_1play_1_1DefendShot" ],
            [ "KeeperKickBall", "classrtt_1_1ai_1_1stp_1_1play_1_1KeeperKickBall.html", "classrtt_1_1ai_1_1stp_1_1play_1_1KeeperKickBall" ],
            [ "Attack", "classrtt_1_1ai_1_1stp_1_1play_1_1Attack.html", "classrtt_1_1ai_1_1stp_1_1play_1_1Attack" ],
            [ "AttackingPass", "classrtt_1_1ai_1_1stp_1_1play_1_1AttackingPass.html", "classrtt_1_1ai_1_1stp_1_1play_1_1AttackingPass" ],
            [ "GenericPass", "classrtt_1_1ai_1_1stp_1_1play_1_1GenericPass.html", "classrtt_1_1ai_1_1stp_1_1play_1_1GenericPass" ],
            [ "PlayTemplate", "classrtt_1_1ai_1_1stp_1_1play_1_1PlayTemplate.html", "classrtt_1_1ai_1_1stp_1_1play_1_1PlayTemplate" ],
            [ "AggressiveStopFormation", "classrtt_1_1ai_1_1stp_1_1play_1_1AggressiveStopFormation.html", "classrtt_1_1ai_1_1stp_1_1play_1_1AggressiveStopFormation" ],
            [ "BallPlacementThem", "classrtt_1_1ai_1_1stp_1_1play_1_1BallPlacementThem.html", "classrtt_1_1ai_1_1stp_1_1play_1_1BallPlacementThem" ],
            [ "BallPlacementUs", "classrtt_1_1ai_1_1stp_1_1play_1_1BallPlacementUs.html", "classrtt_1_1ai_1_1stp_1_1play_1_1BallPlacementUs" ],
            [ "DefensiveStopFormation", "classrtt_1_1ai_1_1stp_1_1play_1_1DefensiveStopFormation.html", "classrtt_1_1ai_1_1stp_1_1play_1_1DefensiveStopFormation" ],
            [ "FormationPreHalf", "classrtt_1_1ai_1_1stp_1_1play_1_1FormationPreHalf.html", "classrtt_1_1ai_1_1stp_1_1play_1_1FormationPreHalf" ],
            [ "FreeKickThem", "classrtt_1_1ai_1_1stp_1_1play_1_1FreeKickThem.html", "classrtt_1_1ai_1_1stp_1_1play_1_1FreeKickThem" ],
            [ "FreeKickUsAtGoal", "classrtt_1_1ai_1_1stp_1_1play_1_1FreeKickUsAtGoal.html", "classrtt_1_1ai_1_1stp_1_1play_1_1FreeKickUsAtGoal" ],
            [ "FreeKickUsPass", "classrtt_1_1ai_1_1stp_1_1play_1_1FreeKickUsPass.html", "classrtt_1_1ai_1_1stp_1_1play_1_1FreeKickUsPass" ],
            [ "Halt", "classrtt_1_1ai_1_1stp_1_1play_1_1Halt.html", "classrtt_1_1ai_1_1stp_1_1play_1_1Halt" ],
            [ "KickOffThem", "classrtt_1_1ai_1_1stp_1_1play_1_1KickOffThem.html", "classrtt_1_1ai_1_1stp_1_1play_1_1KickOffThem" ],
            [ "KickOffThemPrepare", "classrtt_1_1ai_1_1stp_1_1play_1_1KickOffThemPrepare.html", "classrtt_1_1ai_1_1stp_1_1play_1_1KickOffThemPrepare" ],
            [ "KickOffUs", "classrtt_1_1ai_1_1stp_1_1play_1_1KickOffUs.html", "classrtt_1_1ai_1_1stp_1_1play_1_1KickOffUs" ],
            [ "KickOffUsPrepare", "classrtt_1_1ai_1_1stp_1_1play_1_1KickOffUsPrepare.html", "classrtt_1_1ai_1_1stp_1_1play_1_1KickOffUsPrepare" ],
            [ "PenaltyThem", "classrtt_1_1ai_1_1stp_1_1play_1_1PenaltyThem.html", "classrtt_1_1ai_1_1stp_1_1play_1_1PenaltyThem" ],
            [ "PenaltyThemPrepare", "classrtt_1_1ai_1_1stp_1_1play_1_1PenaltyThemPrepare.html", "classrtt_1_1ai_1_1stp_1_1play_1_1PenaltyThemPrepare" ],
            [ "PenaltyUs", "classrtt_1_1ai_1_1stp_1_1play_1_1PenaltyUs.html", "classrtt_1_1ai_1_1stp_1_1play_1_1PenaltyUs" ],
            [ "PenaltyUsPrepare", "classrtt_1_1ai_1_1stp_1_1play_1_1PenaltyUsPrepare.html", "classrtt_1_1ai_1_1stp_1_1play_1_1PenaltyUsPrepare" ],
            [ "TimeOut", "classrtt_1_1ai_1_1stp_1_1play_1_1TimeOut.html", "classrtt_1_1ai_1_1stp_1_1play_1_1TimeOut" ],
            [ "ReflectKick", "classrtt_1_1ai_1_1stp_1_1play_1_1ReflectKick.html", "classrtt_1_1ai_1_1stp_1_1play_1_1ReflectKick" ]
          ] ],
          [ "role", "namespacertt_1_1ai_1_1stp_1_1role.html", [
            [ "Attacker", "classrtt_1_1ai_1_1stp_1_1role_1_1Attacker.html", "classrtt_1_1ai_1_1stp_1_1role_1_1Attacker" ],
            [ "BallGetter", "classrtt_1_1ai_1_1stp_1_1role_1_1BallGetter.html", "classrtt_1_1ai_1_1stp_1_1role_1_1BallGetter" ],
            [ "BallPlacer", "classrtt_1_1ai_1_1stp_1_1role_1_1BallPlacer.html", "classrtt_1_1ai_1_1stp_1_1role_1_1BallPlacer" ],
            [ "BallReflector", "classrtt_1_1ai_1_1stp_1_1role_1_1BallReflector.html", "classrtt_1_1ai_1_1stp_1_1role_1_1BallReflector" ],
            [ "FreeKickTaker", "classrtt_1_1ai_1_1stp_1_1role_1_1FreeKickTaker.html", "classrtt_1_1ai_1_1stp_1_1role_1_1FreeKickTaker" ],
            [ "Harasser", "classrtt_1_1ai_1_1stp_1_1role_1_1Harasser.html", "classrtt_1_1ai_1_1stp_1_1role_1_1Harasser" ],
            [ "KeeperPasser", "classrtt_1_1ai_1_1stp_1_1role_1_1KeeperPasser.html", "classrtt_1_1ai_1_1stp_1_1role_1_1KeeperPasser" ],
            [ "Passer", "classrtt_1_1ai_1_1stp_1_1role_1_1Passer.html", "classrtt_1_1ai_1_1stp_1_1role_1_1Passer" ],
            [ "PassReceiver", "classrtt_1_1ai_1_1stp_1_1role_1_1PassReceiver.html", "classrtt_1_1ai_1_1stp_1_1role_1_1PassReceiver" ],
            [ "Keeper", "classrtt_1_1ai_1_1stp_1_1role_1_1Keeper.html", "classrtt_1_1ai_1_1stp_1_1role_1_1Keeper" ],
            [ "BallAvoider", "classrtt_1_1ai_1_1stp_1_1role_1_1BallAvoider.html", "classrtt_1_1ai_1_1stp_1_1role_1_1BallAvoider" ],
            [ "BallDefender", "classrtt_1_1ai_1_1stp_1_1role_1_1BallDefender.html", "classrtt_1_1ai_1_1stp_1_1role_1_1BallDefender" ],
            [ "Formation", "classrtt_1_1ai_1_1stp_1_1role_1_1Formation.html", "classrtt_1_1ai_1_1stp_1_1role_1_1Formation" ],
            [ "Halt", "classrtt_1_1ai_1_1stp_1_1role_1_1Halt.html", "classrtt_1_1ai_1_1stp_1_1role_1_1Halt" ],
            [ "RobotDefender", "classrtt_1_1ai_1_1stp_1_1role_1_1RobotDefender.html", "classrtt_1_1ai_1_1stp_1_1role_1_1RobotDefender" ],
            [ "Waller", "classrtt_1_1ai_1_1stp_1_1role_1_1Waller.html", "classrtt_1_1ai_1_1stp_1_1role_1_1Waller" ],
            [ "PenaltyKeeper", "classrtt_1_1ai_1_1stp_1_1role_1_1PenaltyKeeper.html", "classrtt_1_1ai_1_1stp_1_1role_1_1PenaltyKeeper" ]
          ] ],
          [ "skill", "namespacertt_1_1ai_1_1stp_1_1skill.html", [
            [ "Chip", "classrtt_1_1ai_1_1stp_1_1skill_1_1Chip.html", "classrtt_1_1ai_1_1stp_1_1skill_1_1Chip" ],
            [ "GoToPos", "classrtt_1_1ai_1_1stp_1_1skill_1_1GoToPos.html", "classrtt_1_1ai_1_1stp_1_1skill_1_1GoToPos" ],
            [ "Kick", "classrtt_1_1ai_1_1stp_1_1skill_1_1Kick.html", "classrtt_1_1ai_1_1stp_1_1skill_1_1Kick" ],
            [ "Orbit", "classrtt_1_1ai_1_1stp_1_1skill_1_1Orbit.html", "classrtt_1_1ai_1_1stp_1_1skill_1_1Orbit" ],
            [ "OrbitAngular", "classrtt_1_1ai_1_1stp_1_1skill_1_1OrbitAngular.html", "classrtt_1_1ai_1_1stp_1_1skill_1_1OrbitAngular" ],
            [ "Rotate", "classrtt_1_1ai_1_1stp_1_1skill_1_1Rotate.html", "classrtt_1_1ai_1_1stp_1_1skill_1_1Rotate" ],
            [ "Shoot", "classrtt_1_1ai_1_1stp_1_1skill_1_1Shoot.html", "classrtt_1_1ai_1_1stp_1_1skill_1_1Shoot" ],
            [ "TestSkill", "classrtt_1_1ai_1_1stp_1_1skill_1_1TestSkill.html", "classrtt_1_1ai_1_1stp_1_1skill_1_1TestSkill" ]
          ] ],
          [ "tactic", "namespacertt_1_1ai_1_1stp_1_1tactic.html", [
            [ "ChipAtPos", "classrtt_1_1ai_1_1stp_1_1tactic_1_1ChipAtPos.html", "classrtt_1_1ai_1_1stp_1_1tactic_1_1ChipAtPos" ],
            [ "DriveWithBall", "classrtt_1_1ai_1_1stp_1_1tactic_1_1DriveWithBall.html", "classrtt_1_1ai_1_1stp_1_1tactic_1_1DriveWithBall" ],
            [ "GetBall", "classrtt_1_1ai_1_1stp_1_1tactic_1_1GetBall.html", "classrtt_1_1ai_1_1stp_1_1tactic_1_1GetBall" ],
            [ "GetBehindBallInDirection", "classrtt_1_1ai_1_1stp_1_1tactic_1_1GetBehindBallInDirection.html", "classrtt_1_1ai_1_1stp_1_1tactic_1_1GetBehindBallInDirection" ],
            [ "KickAtPos", "classrtt_1_1ai_1_1stp_1_1tactic_1_1KickAtPos.html", "classrtt_1_1ai_1_1stp_1_1tactic_1_1KickAtPos" ],
            [ "OrbitKick", "classrtt_1_1ai_1_1stp_1_1tactic_1_1OrbitKick.html", "classrtt_1_1ai_1_1stp_1_1tactic_1_1OrbitKick" ],
            [ "Receive", "classrtt_1_1ai_1_1stp_1_1tactic_1_1Receive.html", "classrtt_1_1ai_1_1stp_1_1tactic_1_1Receive" ],
            [ "ShootAtPos", "classrtt_1_1ai_1_1stp_1_1tactic_1_1ShootAtPos.html", "classrtt_1_1ai_1_1stp_1_1tactic_1_1ShootAtPos" ],
            [ "Intercept", "classrtt_1_1ai_1_1stp_1_1tactic_1_1Intercept.html", "classrtt_1_1ai_1_1stp_1_1tactic_1_1Intercept" ],
            [ "KeeperBlockBall", "classrtt_1_1ai_1_1stp_1_1tactic_1_1KeeperBlockBall.html", "classrtt_1_1ai_1_1stp_1_1tactic_1_1KeeperBlockBall" ],
            [ "AvoidBall", "classrtt_1_1ai_1_1stp_1_1tactic_1_1AvoidBall.html", "classrtt_1_1ai_1_1stp_1_1tactic_1_1AvoidBall" ],
            [ "BallStandBack", "classrtt_1_1ai_1_1stp_1_1tactic_1_1BallStandBack.html", "classrtt_1_1ai_1_1stp_1_1tactic_1_1BallStandBack" ],
            [ "BlockBall", "classrtt_1_1ai_1_1stp_1_1tactic_1_1BlockBall.html", "classrtt_1_1ai_1_1stp_1_1tactic_1_1BlockBall" ],
            [ "BlockRobot", "classrtt_1_1ai_1_1stp_1_1tactic_1_1BlockRobot.html", "classrtt_1_1ai_1_1stp_1_1tactic_1_1BlockRobot" ],
            [ "Formation", "classrtt_1_1ai_1_1stp_1_1tactic_1_1Formation.html", "classrtt_1_1ai_1_1stp_1_1tactic_1_1Formation" ],
            [ "Halt", "classrtt_1_1ai_1_1stp_1_1tactic_1_1Halt.html", "classrtt_1_1ai_1_1stp_1_1tactic_1_1Halt" ],
            [ "Walling", "classrtt_1_1ai_1_1stp_1_1tactic_1_1Walling.html", "classrtt_1_1ai_1_1stp_1_1tactic_1_1Walling" ],
            [ "PositionAndAim", "classrtt_1_1ai_1_1stp_1_1tactic_1_1PositionAndAim.html", "classrtt_1_1ai_1_1stp_1_1tactic_1_1PositionAndAim" ]
          ] ],
          [ "ComputationManager", "classrtt_1_1ai_1_1stp_1_1ComputationManager.html", "classrtt_1_1ai_1_1stp_1_1ComputationManager" ],
          [ "PassInfo", "namespacertt_1_1ai_1_1stp.html#structrtt_1_1ai_1_1stp_1_1PassInfo", "namespacertt_1_1ai_1_1stp_structrtt_1_1ai_1_1stp_1_1PassInfo_dup" ],
          [ "PositionComputations", "classrtt_1_1ai_1_1stp_1_1PositionComputations.html", "classrtt_1_1ai_1_1stp_1_1PositionComputations" ],
          [ "PositionScoring", "classrtt_1_1ai_1_1stp_1_1PositionScoring.html", "classrtt_1_1ai_1_1stp_1_1PositionScoring" ],
          [ "Play", "classrtt_1_1ai_1_1stp_1_1Play.html", "classrtt_1_1ai_1_1stp_1_1Play" ],
          [ "PlayDecider", "classrtt_1_1ai_1_1stp_1_1PlayDecider.html", "classrtt_1_1ai_1_1stp_1_1PlayDecider" ],
          [ "PlayEvaluator", "classrtt_1_1ai_1_1stp_1_1PlayEvaluator.html", "classrtt_1_1ai_1_1stp_1_1PlayEvaluator" ],
          [ "TestPlay", "classrtt_1_1ai_1_1stp_1_1TestPlay.html", "classrtt_1_1ai_1_1stp_1_1TestPlay" ],
          [ "Role", "classrtt_1_1ai_1_1stp_1_1Role.html", "classrtt_1_1ai_1_1stp_1_1Role" ],
          [ "TestRole", "classrtt_1_1ai_1_1stp_1_1TestRole.html", "classrtt_1_1ai_1_1stp_1_1TestRole" ],
          [ "Skill", "classrtt_1_1ai_1_1stp_1_1Skill.html", "classrtt_1_1ai_1_1stp_1_1Skill" ],
          [ "StpInfo", "structrtt_1_1ai_1_1stp_1_1StpInfo.html", "structrtt_1_1ai_1_1stp_1_1StpInfo" ],
          [ "Tactic", "classrtt_1_1ai_1_1stp_1_1Tactic.html", "classrtt_1_1ai_1_1stp_1_1Tactic" ],
          [ "TestTactic", "classrtt_1_1ai_1_1stp_1_1TestTactic.html", "classrtt_1_1ai_1_1stp_1_1TestTactic" ],
          [ "AvoidObjects", "namespacertt_1_1ai_1_1stp.html#structrtt_1_1ai_1_1stp_1_1AvoidObjects", "namespacertt_1_1ai_1_1stp_structrtt_1_1ai_1_1stp_1_1AvoidObjects_dup" ]
        ] ],
        [ "Constants", "classrtt_1_1ai_1_1Constants.html", "classrtt_1_1ai_1_1Constants" ],
        [ "Dealer", "classrtt_1_1ai_1_1Dealer.html", "classrtt_1_1ai_1_1Dealer" ],
        [ "GameState", "structrtt_1_1ai_1_1GameState.html", "structrtt_1_1ai_1_1GameState" ],
        [ "GameStateManager", "classrtt_1_1ai_1_1GameStateManager.html", "classrtt_1_1ai_1_1GameStateManager" ],
        [ "Pause", "classrtt_1_1ai_1_1Pause.html", "classrtt_1_1ai_1_1Pause" ],
        [ "RefGameState", "structrtt_1_1ai_1_1RefGameState.html", "structrtt_1_1ai_1_1RefGameState" ],
        [ "RuleSet", "structrtt_1_1ai_1_1RuleSet.html", "structrtt_1_1ai_1_1RuleSet" ],
        [ "StrategyManager", "classrtt_1_1ai_1_1StrategyManager.html", "classrtt_1_1ai_1_1StrategyManager" ],
        [ "BallPossession", "classrtt_1_1ai_1_1BallPossession.html", "classrtt_1_1ai_1_1BallPossession" ],
        [ "FieldComputations", "classrtt_1_1ai_1_1FieldComputations.html", "classrtt_1_1ai_1_1FieldComputations" ]
      ] ],
      [ "BB", "namespacertt_1_1BB.html", [
        [ "BBTrajectoryPart", "namespacertt_1_1BB.html#structrtt_1_1BB_1_1BBTrajectoryPart", "namespacertt_1_1BB_structrtt_1_1BB_1_1BBTrajectoryPart_dup" ],
        [ "BBPosVelAcc", "structrtt_1_1BB_1_1BBPosVelAcc.html", "structrtt_1_1BB_1_1BBPosVelAcc" ],
        [ "BBTrajectory1D", "classrtt_1_1BB_1_1BBTrajectory1D.html", "classrtt_1_1BB_1_1BBTrajectory1D" ],
        [ "BBTrajectory2D", "classrtt_1_1BB_1_1BBTrajectory2D.html", "classrtt_1_1BB_1_1BBTrajectory2D" ],
        [ "CollisionData", "namespacertt_1_1BB.html#structrtt_1_1BB_1_1CollisionData", "namespacertt_1_1BB_structrtt_1_1BB_1_1CollisionData_dup" ],
        [ "CommandCollision", "namespacertt_1_1BB.html#structrtt_1_1BB_1_1CommandCollision", "namespacertt_1_1BB_structrtt_1_1BB_1_1CommandCollision_dup" ],
        [ "WorldObjects", "classrtt_1_1BB_1_1WorldObjects.html", "classrtt_1_1BB_1_1WorldObjects" ]
      ] ],
      [ "input", "namespacertt_1_1input.html", [
        [ "JoystickHandler", "classrtt_1_1input_1_1JoystickHandler.html", "classrtt_1_1input_1_1JoystickHandler" ],
        [ "JoystickManager", "classrtt_1_1input_1_1JoystickManager.html", "classrtt_1_1input_1_1JoystickManager" ],
        [ "JoystickState", "namespacertt_1_1input.html#classrtt_1_1input_1_1JoystickState", "namespacertt_1_1input_classrtt_1_1input_1_1JoystickState_dup" ]
      ] ],
      [ "Interface", "namespacertt_1_1Interface.html", [
        [ "InterfaceControllerServer", "classrtt_1_1Interface_1_1InterfaceControllerServer.html", "classrtt_1_1Interface_1_1InterfaceControllerServer" ]
      ] ],
      [ "world", "namespacertt_1_1world.html", [
        [ "ball", "namespacertt_1_1world_1_1ball.html", [
          [ "Ball", "classrtt_1_1world_1_1ball_1_1Ball.html", "classrtt_1_1world_1_1ball_1_1Ball" ]
        ] ],
        [ "robot", "namespacertt_1_1world_1_1robot.html", [
          [ "hasBallInfo", "namespacertt_1_1world_1_1robot.html#structrtt_1_1world_1_1robot_1_1hasBallInfo", "namespacertt_1_1world_1_1robot_structrtt_1_1world_1_1robot_1_1hasBallInfo_dup" ],
          [ "Robot", "classrtt_1_1world_1_1robot_1_1Robot.html", "classrtt_1_1world_1_1robot_1_1Robot" ]
        ] ],
        [ "view", "namespacertt_1_1world_1_1view.html", [
          [ "BallView", "classrtt_1_1world_1_1view_1_1BallView.html", "classrtt_1_1world_1_1view_1_1BallView" ],
          [ "RobotView", "classrtt_1_1world_1_1view_1_1RobotView.html", "classrtt_1_1world_1_1view_1_1RobotView" ],
          [ "WorldDataView", "classrtt_1_1world_1_1view_1_1WorldDataView.html", "classrtt_1_1world_1_1view_1_1WorldDataView" ]
        ] ],
        [ "FieldLineSegment", "namespacertt_1_1world.html#structrtt_1_1world_1_1FieldLineSegment", "namespacertt_1_1world_structrtt_1_1world_1_1FieldLineSegment_dup" ],
        [ "FieldArc", "namespacertt_1_1world.html#structrtt_1_1world_1_1FieldArc", "namespacertt_1_1world_structrtt_1_1world_1_1FieldArc_dup" ],
        [ "Field", "classrtt_1_1world_1_1Field.html", "classrtt_1_1world_1_1Field" ],
        [ "World", "classrtt_1_1world_1_1World.html", "classrtt_1_1world_1_1World" ],
        [ "WorldData", "classrtt_1_1world_1_1WorldData.html", "classrtt_1_1world_1_1WorldData" ]
      ] ],
      [ "AnglePID", "classrtt_1_1AnglePID.html", "classrtt_1_1AnglePID" ],
      [ "Trajectory1D", "classrtt_1_1Trajectory1D.html", "classrtt_1_1Trajectory1D" ],
      [ "Trajectory2D", "classrtt_1_1Trajectory2D.html", "classrtt_1_1Trajectory2D" ],
      [ "STPManager", "classrtt_1_1STPManager.html", "classrtt_1_1STPManager" ],
      [ "Settings", "classrtt_1_1Settings.html", "classrtt_1_1Settings" ]
    ] ],
    [ "testhelpers", "namespacetesthelpers.html", [
      [ "FieldHelper", "classtesthelpers_1_1FieldHelper.html", "classtesthelpers_1_1FieldHelper" ],
      [ "WorldHelper", "classtesthelpers_1_1WorldHelper.html", "classtesthelpers_1_1WorldHelper" ]
    ] ],
    [ "jcv_cast_align_struct", "Voronoi_8h.html#unionjcv__cast__align__struct", "Voronoi_8h_unionjcv__cast__align__struct" ],
    [ "jcv_clipper", "Voronoi_8h.html#struct__jcv__clipper", "Voronoi_8h_struct__jcv__clipper" ],
    [ "jcv_context_internal", "Voronoi_8h.html#struct__jcv__context__internal", "Voronoi_8h_struct__jcv__context__internal" ],
    [ "jcv_diagram", "Voronoi_8h.html#struct__jcv__diagram", "Voronoi_8h_struct__jcv__diagram" ],
    [ "jcv_edge", "Voronoi_8h.html#struct__jcv__edge", "Voronoi_8h_struct__jcv__edge" ],
    [ "jcv_graphedge", "Voronoi_8h.html#struct__jcv__graphedge", "Voronoi_8h_struct__jcv__graphedge" ],
    [ "jcv_halfedge", "Voronoi_8h.html#structjcv__halfedge", "Voronoi_8h_structjcv__halfedge" ],
    [ "jcv_memoryblock", "Voronoi_8h.html#structjcv__memoryblock", "Voronoi_8h_structjcv__memoryblock" ],
    [ "jcv_point", "Voronoi_8h.html#struct__jcv__point", "Voronoi_8h_struct__jcv__point" ],
    [ "jcv_priorityqueue", "Voronoi_8h.html#structjcv__priorityqueue", "Voronoi_8h_structjcv__priorityqueue" ],
    [ "jcv_rect", "Voronoi_8h.html#struct__jcv__rect", "Voronoi_8h_struct__jcv__rect" ],
    [ "jcv_site", "Voronoi_8h.html#struct__jcv__site", "Voronoi_8h_struct__jcv__site" ],
    [ "MockTactic", "classMockTactic.html", "classMockTactic" ],
    [ "RTT_AI_Tests", "classRTT__AI__Tests.html", "classRTT__AI__Tests" ],
    [ "TestSkill", "classTestSkill.html", "classTestSkill" ]
];