//
// Created by mrlukasbos on 23-10-18.
//

#ifndef ROBOTEAM_AI_CONSTANTS_H
#define ROBOTEAM_AI_CONSTANTS_H

#define DEFAULT_KICK_POWER 5.0
#define MAX_KICK_CYCLES 20
#define MAX_ANGULAR_VELOCITY 1.0;




#endif //ROBOTEAM_AI_CONSTANTS_H
